name: Build firmware

on:
  push:
    branches: ['**']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:trixie

    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          apt update
          apt install make gcc sdcc xxd python-is-python3 libjson-c-dev zlib1g-dev -y
      - name: Run the host-side unit tests
        run: make -C test
      - name: Check if machine.c can be compiled for all machines
        run: make machine_check
      - name: Make project
        run: make MACHINE="KP_9000_6XHML_X2"
